name: Deploy Application
on :
  push:
    branches:
      - main

# Define variables we can reuse throughout the pipeline
env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: wordpress-hosting-ecr-repo

jobs: 
  build-and-push:
    name : build image and push to aws 
    runs-on: ubuntu-latest

    steps:
    # 1. Download your code onto the GitHub server
      - name: Checkout code 
        uses: actions/checkout@v4
      # 2. Log into AWS using the secrets you just saved
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_REGION}}

      # 3. Log the Docker client into your specific ECR Registry
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

        # 4. Build the image and push it!
      - name: Build, Tag, and Push Docker Image
        env: 
          # This grabs the secure registry URL from step 3
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          # This creates a unique tag using the Git Commit ID (e.g., a1b2c3d)
          IMAGE_TAG: ${{github.sha}}

        run: |
            echo "moving to docker folder"
            cd docker 

            echo "Building docker image"
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          # echo "Pushing image to ecr repo"
            # docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
          
          # 5. THE SECURITY GATE: Scan the local image with Trivy
      - name: Run Trivy vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}'
          format: 'table'
          # If it finds CRITICAL flaws, crash the pipeline (exit-code 1)
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      # 6. PUSH to ECR (Only runs if Step 5 passes)
      - name: Push Image to ECR
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
            docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
# 7. THE MATRIX CANARY (CD): Deploy to Canary, Verify, then Global Rollout
      - name: Matrix Canary Deployment
        run: |
          echo "Initiating Canary Deployment..."
          aws ecs update-service --cluster wordpress-hosting-cluster --service wordpress-hosting-client3-service --force-new-deployment --no-cli-pager

          echo "waiting for canary (client 3) container to stabilize (this take ~3 minutes)"
          aws ecs wait services-stable --cluster wordpress-hosting-cluster --services wordpress-hosting-client3-service

          echo "performing HTTP health check on canary"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -L https://client3.babu-lahade.online)

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "Canary is HEALTHY (Status 200). The code is safe. Proceeding with Global Rollout!"

            # The safe list of remaining clients
            CLIENTS=("client4")
            for CLIENT in "${CLIENTS[@]}";do
              echo "deploying to  ${CLIENT}"
              aws ecs update-service --cluster wordpress-hosting-cluster --service wordpress-hosting-client3-service --force-new-deployment --no-cli-pager
            done 
            echo "Matrix Global Rollout Complete"

          else
            echo "CRITICAL: Canary failed with HTTP Status $HTTP_STATUS, Halting Global Rollout to protect other clients!"
            exit 1 # This command instantly crashes the GitHub pipeline so it stops
          fi 


